{-# LANGUAGE FlexibleInstances, OverloadedStrings, DefaultSignatures #-}

module Values where

import Data.Aeson
import Data.Text (Text)
import Data.Word as W
import Data.Int as I
import Control.Exception
import qualified Data.ByteString.Lazy as LBS

-- Typeable things are convertible to our format
class Typeable a where
    toType :: a -> String
    toType a = "unknown"
    toJson :: a -> Value
    default toJson :: ToJSON a => a -> Value
    toJson = toJSON

-- We support maybe as the null value
instance (Typeable a) => Typeable (Maybe a) where
    toType m = case m of
        Just n -> toType n
        Nothing -> "nothing"
    toJson m = case m of
        Just n -> toJson n
        Nothing -> Null
instance Typeable W.Word8 where toType _ = "uint8"
instance Typeable W.Word16 where toType _ = "uint16"
instance Typeable W.Word32 where toType _ = "uint32"
instance Typeable W.Word64 where toType _ = "uint64"
instance Typeable I.Int8 where toType _ = "int8"
instance Typeable I.Int16 where toType _ = "int16"
instance Typeable I.Int32 where toType _ = "int32"
instance Typeable I.Int64 where toType _ = "int64"

instance Typeable Float where toType _ = "single_precision"
instance Typeable Double where toType _ = "double_precision"
instance Typeable Integer where toType _ = "bigint"

instance Typeable Bool where toType _ = "boolean"

instance Typeable Text where toType _ = "text"
instance {-# OVERLAPPABLE #-} Typeable String where toType _ = "text"

instance {-# OVERLAPPABLE #-} Typeable a => Typeable [a] where
    toType m = "sequence"
    toJson = toJSON . map toJson

-- Tuples, up to 62 items, as in GHC
instance () => Typeable () where
    toType m = "tuple"
    toJson () = toJSON ()
instance (Typeable a, Typeable b) => Typeable (a, b) where
    toType m = "tuple"
    toJson (a, b) = toJSON [toJson a, toJson b]
instance (Typeable a, Typeable b, Typeable c) => Typeable (a, b, c) where
    toType m = "tuple"
    toJson (a, b, c) = toJSON [toJson a, toJson b, toJson c]
instance (Typeable a, Typeable b, Typeable c, Typeable d) => Typeable (a, b, c, d) where
    toType m = "tuple"
    toJson (a, b, c, d) = toJSON [toJson a, toJson b, toJson c, toJson d]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e) => Typeable (a, b, c, d, e) where
    toType m = "tuple"
    toJson (a, b, c, d, e) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f) => Typeable (a, b, c, d, e, f) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g) => Typeable (a, b, c, d, e, f, g) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h) => Typeable (a, b, c, d, e, f, g, h) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i) => Typeable (a, b, c, d, e, f, g, h, i) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j) => Typeable (a, b, c, d, e, f, g, h, i, j) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k) => Typeable (a, b, c, d, e, f, g, h, i, j, k) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai, toJson aj]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai, toJson aj, toJson ak]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai, toJson aj, toJson ak, toJson al]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai, toJson aj, toJson ak, toJson al, toJson am]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai, toJson aj, toJson ak, toJson al, toJson am, toJson an]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai, toJson aj, toJson ak, toJson al, toJson am, toJson an, toJson ao]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai, toJson aj, toJson ak, toJson al, toJson am, toJson an, toJson ao, toJson ap]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai, toJson aj, toJson ak, toJson al, toJson am, toJson an, toJson ao, toJson ap, toJson aq]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai, toJson aj, toJson ak, toJson al, toJson am, toJson an, toJson ao, toJson ap, toJson aq, toJson ar]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai, toJson aj, toJson ak, toJson al, toJson am, toJson an, toJson ao, toJson ap, toJson aq, toJson ar, toJson as]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai, toJson aj, toJson ak, toJson al, toJson am, toJson an, toJson ao, toJson ap, toJson aq, toJson ar, toJson as, toJson at]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai, toJson aj, toJson ak, toJson al, toJson am, toJson an, toJson ao, toJson ap, toJson aq, toJson ar, toJson as, toJson at, toJson au]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai, toJson aj, toJson ak, toJson al, toJson am, toJson an, toJson ao, toJson ap, toJson aq, toJson ar, toJson as, toJson at, toJson au, toJson av]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av, Typeable aw) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai, toJson aj, toJson ak, toJson al, toJson am, toJson an, toJson ao, toJson ap, toJson aq, toJson ar, toJson as, toJson at, toJson au, toJson av, toJson aw]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av, Typeable aw, Typeable ax) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai, toJson aj, toJson ak, toJson al, toJson am, toJson an, toJson ao, toJson ap, toJson aq, toJson ar, toJson as, toJson at, toJson au, toJson av, toJson aw, toJson ax]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av, Typeable aw, Typeable ax, Typeable ay) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai, toJson aj, toJson ak, toJson al, toJson am, toJson an, toJson ao, toJson ap, toJson aq, toJson ar, toJson as, toJson at, toJson au, toJson av, toJson aw, toJson ax, toJson ay]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av, Typeable aw, Typeable ax, Typeable ay, Typeable az) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai, toJson aj, toJson ak, toJson al, toJson am, toJson an, toJson ao, toJson ap, toJson aq, toJson ar, toJson as, toJson at, toJson au, toJson av, toJson aw, toJson ax, toJson ay, toJson az]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av, Typeable aw, Typeable ax, Typeable ay, Typeable az, Typeable ba) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai, toJson aj, toJson ak, toJson al, toJson am, toJson an, toJson ao, toJson ap, toJson aq, toJson ar, toJson as, toJson at, toJson au, toJson av, toJson aw, toJson ax, toJson ay, toJson az, toJson ba]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av, Typeable aw, Typeable ax, Typeable ay, Typeable az, Typeable ba, Typeable bb) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai, toJson aj, toJson ak, toJson al, toJson am, toJson an, toJson ao, toJson ap, toJson aq, toJson ar, toJson as, toJson at, toJson au, toJson av, toJson aw, toJson ax, toJson ay, toJson az, toJson ba, toJson bb]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av, Typeable aw, Typeable ax, Typeable ay, Typeable az, Typeable ba, Typeable bb, Typeable bc) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai, toJson aj, toJson ak, toJson al, toJson am, toJson an, toJson ao, toJson ap, toJson aq, toJson ar, toJson as, toJson at, toJson au, toJson av, toJson aw, toJson ax, toJson ay, toJson az, toJson ba, toJson bb, toJson bc]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av, Typeable aw, Typeable ax, Typeable ay, Typeable az, Typeable ba, Typeable bb, Typeable bc, Typeable bd) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai, toJson aj, toJson ak, toJson al, toJson am, toJson an, toJson ao, toJson ap, toJson aq, toJson ar, toJson as, toJson at, toJson au, toJson av, toJson aw, toJson ax, toJson ay, toJson az, toJson ba, toJson bb, toJson bc, toJson bd]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av, Typeable aw, Typeable ax, Typeable ay, Typeable az, Typeable ba, Typeable bb, Typeable bc, Typeable bd, Typeable be) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai, toJson aj, toJson ak, toJson al, toJson am, toJson an, toJson ao, toJson ap, toJson aq, toJson ar, toJson as, toJson at, toJson au, toJson av, toJson aw, toJson ax, toJson ay, toJson az, toJson ba, toJson bb, toJson bc, toJson bd, toJson be]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av, Typeable aw, Typeable ax, Typeable ay, Typeable az, Typeable ba, Typeable bb, Typeable bc, Typeable bd, Typeable be, Typeable bf) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be, bf) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be, bf) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai, toJson aj, toJson ak, toJson al, toJson am, toJson an, toJson ao, toJson ap, toJson aq, toJson ar, toJson as, toJson at, toJson au, toJson av, toJson aw, toJson ax, toJson ay, toJson az, toJson ba, toJson bb, toJson bc, toJson bd, toJson be, toJson bf]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av, Typeable aw, Typeable ax, Typeable ay, Typeable az, Typeable ba, Typeable bb, Typeable bc, Typeable bd, Typeable be, Typeable bf, Typeable bg) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be, bf, bg) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be, bf, bg) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai, toJson aj, toJson ak, toJson al, toJson am, toJson an, toJson ao, toJson ap, toJson aq, toJson ar, toJson as, toJson at, toJson au, toJson av, toJson aw, toJson ax, toJson ay, toJson az, toJson ba, toJson bb, toJson bc, toJson bd, toJson be, toJson bf, toJson bg]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av, Typeable aw, Typeable ax, Typeable ay, Typeable az, Typeable ba, Typeable bb, Typeable bc, Typeable bd, Typeable be, Typeable bf, Typeable bg, Typeable bh) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be, bf, bg, bh) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be, bf, bg, bh) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai, toJson aj, toJson ak, toJson al, toJson am, toJson an, toJson ao, toJson ap, toJson aq, toJson ar, toJson as, toJson at, toJson au, toJson av, toJson aw, toJson ax, toJson ay, toJson az, toJson ba, toJson bb, toJson bc, toJson bd, toJson be, toJson bf, toJson bg, toJson bh]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av, Typeable aw, Typeable ax, Typeable ay, Typeable az, Typeable ba, Typeable bb, Typeable bc, Typeable bd, Typeable be, Typeable bf, Typeable bg, Typeable bh, Typeable bi) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be, bf, bg, bh, bi) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be, bf, bg, bh, bi) = toJSON [toJson a, toJson b, toJson c, toJson d, toJson e, toJson f, toJson g, toJson h, toJson i, toJson j, toJson k, toJson l, toJson m, toJson n, toJson o, toJson p, toJson q, toJson r, toJson s, toJson t, toJson u, toJson v, toJson w, toJson x, toJson y, toJson z, toJson aa, toJson ab, toJson ac, toJson ad, toJson ae, toJson af, toJson ag, toJson ah, toJson ai, toJson aj, toJson ak, toJson al, toJson am, toJson an, toJson ao, toJson ap, toJson aq, toJson ar, toJson as, toJson at, toJson au, toJson av, toJson aw, toJson ax, toJson ay, toJson az, toJson ba, toJson bb, toJson bc, toJson bd, toJson be, toJson bf, toJson bg, toJson bh, toJson bi]



sendValue :: Typeable a => FilePath -> a -> IO ()
sendValue file value = LBS.appendFile file (encode (object [
        "type" .= toJSON (toType value),
        "data" .= toJson value
    ]))


sendEvaluated :: FilePath -> Bool -> Maybe String -> Maybe String -> [String] -> IO ()
sendEvaluated file result expected actual messages =
    LBS.appendFile file (encode (object [
        "result" .= toJSON result,
        "readable_expected" .= toJSON expected,
        "readable_actual" .= toJSON actual,
        "messages" .= toJSON messages
    ]))

sendException :: Exception e => FilePath -> Maybe e -> IO ()
sendException file (Just ex) = LBS.appendFile file (encode (object [
        "message" .= toJSON (show ex),
        "stacktrace" .= toJSON (show "-")
    ]))
sendException _ Nothing = return ()
