{-# LANGUAGE FlexibleInstances, OverloadedStrings, DefaultSignatures, NamedFieldPuns #-}

module Values where

import Data.Aeson
import Data.Text (Text)
import Data.Word as W
import Data.Int as I
import Control.Exception
import qualified Data.ByteString.Lazy as LBS
import EvaluationUtils
import System.IO (Handle)
import System.IO.Unsafe (unsafePerformIO)


-- Typeable things are convertible to our format
class Typeable a where
    toType :: a -> String
    toType a = "unknown"
    toJson :: a -> Value
    default toJson :: ToJSON a => a -> Value
    toJson = toJSON
    -- Function needed to unwrap IO values without needing calls to unsafeIO
    toJsonIO :: a -> IO (String, Value)
    default toJsonIO :: a -> IO (String, Value)
    toJsonIO a = return ((toType a), (toJson a))

-- We support maybe as the null value
instance (Typeable a) => Typeable (Maybe a) where
    toType m = case m of
        Just n -> toType n
        Nothing -> "nothing"
    toJson m = case m of
        Just n -> toJson n
        Nothing -> Null

instance (Typeable a) => Typeable (IO a) where
    -- Calls to `unsafePerformIO` may not produces the expected results, there for `toJsonIO` is preferred, when called
    -- this function, the student has written no clean haskell code
    {-# NOINLINE toType #-}
    toType = toType . unsafePerformIO
    -- Calls to `unsafePerformIO` may not produces the expected results, there for `toJsonIO` is preferred, when called
    -- this function, the student has written no clean haskell code
    {-# NOINLINE toJson #-}
    toJson = toJson . unsafePerformIO
    -- Preferred function call to pass the IO monad results to the judge, avoid `unsafePerformIO`
    toJsonIO m = do
        unwrapped <- m
        toJsonIO unwrapped

instance Typeable W.Word8 where toType _ = "uint8"
instance Typeable W.Word16 where toType _ = "uint16"
instance Typeable W.Word32 where toType _ = "uint32"
instance Typeable W.Word64 where toType _ = "uint64"
instance Typeable I.Int8 where toType _ = "int8"
instance Typeable I.Int16 where toType _ = "int16"
instance Typeable I.Int32 where toType _ = "int32"
instance Typeable I.Int64 where toType _ = "int64"

instance Typeable Float where toType _ = "single_precision"
instance Typeable Double where toType _ = "double_precision"
instance Typeable Integer where toType _ = "bigint"
instance Typeable Int where toType _ = "integer"

instance Typeable Bool where toType _ = "boolean"
instance Typeable Char where toType _ = "character"

instance Typeable Text where toType _ = "text"
instance {-# OVERLAPPABLE #-} Typeable String where toType _ = "text"

instance {-# OVERLAPPABLE #-} Typeable a => Typeable [a] where
    toType m = "sequence"
    toJson l = toJSON (map toObject l)

-- Tuples, up to 62 items, as in GHC
instance () => Typeable () where
    toType m = "tuple"
    toJson () = toJSON ()
instance (Typeable a, Typeable b) => Typeable (a, b) where
    toType m = "tuple"
    toJson (a, b) = toJSON [toObject a, toObject b]
instance (Typeable a, Typeable b, Typeable c) => Typeable (a, b, c) where
    toType m = "tuple"
    toJson (a, b, c) = toJSON [toObject a, toObject b, toObject c]
instance (Typeable a, Typeable b, Typeable c, Typeable d) => Typeable (a, b, c, d) where
    toType m = "tuple"
    toJson (a, b, c, d) = toJSON [toObject a, toObject b, toObject c, toObject d]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e) => Typeable (a, b, c, d, e) where
    toType m = "tuple"
    toJson (a, b, c, d, e) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f) => Typeable (a, b, c, d, e, f) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g) => Typeable (a, b, c, d, e, f, g) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h) => Typeable (a, b, c, d, e, f, g, h) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i) => Typeable (a, b, c, d, e, f, g, h, i) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j) => Typeable (a, b, c, d, e, f, g, h, i, j) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k) => Typeable (a, b, c, d, e, f, g, h, i, j, k) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av, Typeable aw) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av, toObject aw]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av, Typeable aw, Typeable ax) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av, toObject aw, toObject ax]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av, Typeable aw, Typeable ax, Typeable ay) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av, toObject aw, toObject ax, toObject ay]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av, Typeable aw, Typeable ax, Typeable ay, Typeable az) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av, toObject aw, toObject ax, toObject ay, toObject az]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av, Typeable aw, Typeable ax, Typeable ay, Typeable az, Typeable ba) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av, toObject aw, toObject ax, toObject ay, toObject az, toObject ba]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av, Typeable aw, Typeable ax, Typeable ay, Typeable az, Typeable ba, Typeable bb) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av, toObject aw, toObject ax, toObject ay, toObject az, toObject ba, toObject bb]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av, Typeable aw, Typeable ax, Typeable ay, Typeable az, Typeable ba, Typeable bb, Typeable bc) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av, toObject aw, toObject ax, toObject ay, toObject az, toObject ba, toObject bb, toObject bc]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av, Typeable aw, Typeable ax, Typeable ay, Typeable az, Typeable ba, Typeable bb, Typeable bc, Typeable bd) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av, toObject aw, toObject ax, toObject ay, toObject az, toObject ba, toObject bb, toObject bc, toObject bd]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av, Typeable aw, Typeable ax, Typeable ay, Typeable az, Typeable ba, Typeable bb, Typeable bc, Typeable bd, Typeable be) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av, toObject aw, toObject ax, toObject ay, toObject az, toObject ba, toObject bb, toObject bc, toObject bd, toObject be]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av, Typeable aw, Typeable ax, Typeable ay, Typeable az, Typeable ba, Typeable bb, Typeable bc, Typeable bd, Typeable be, Typeable bf) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be, bf) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be, bf) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av, toObject aw, toObject ax, toObject ay, toObject az, toObject ba, toObject bb, toObject bc, toObject bd, toObject be, toObject bf]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av, Typeable aw, Typeable ax, Typeable ay, Typeable az, Typeable ba, Typeable bb, Typeable bc, Typeable bd, Typeable be, Typeable bf, Typeable bg) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be, bf, bg) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be, bf, bg) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av, toObject aw, toObject ax, toObject ay, toObject az, toObject ba, toObject bb, toObject bc, toObject bd, toObject be, toObject bf, toObject bg]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av, Typeable aw, Typeable ax, Typeable ay, Typeable az, Typeable ba, Typeable bb, Typeable bc, Typeable bd, Typeable be, Typeable bf, Typeable bg, Typeable bh) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be, bf, bg, bh) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be, bf, bg, bh) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av, toObject aw, toObject ax, toObject ay, toObject az, toObject ba, toObject bb, toObject bc, toObject bd, toObject be, toObject bf, toObject bg, toObject bh]
instance (Typeable a, Typeable b, Typeable c, Typeable d, Typeable e, Typeable f, Typeable g, Typeable h, Typeable i, Typeable j, Typeable k, Typeable l, Typeable m, Typeable n, Typeable o, Typeable p, Typeable q, Typeable r, Typeable s, Typeable t, Typeable u, Typeable v, Typeable w, Typeable x, Typeable y, Typeable z, Typeable aa, Typeable ab, Typeable ac, Typeable ad, Typeable ae, Typeable af, Typeable ag, Typeable ah, Typeable ai, Typeable aj, Typeable ak, Typeable al, Typeable am, Typeable an, Typeable ao, Typeable ap, Typeable aq, Typeable ar, Typeable as, Typeable at, Typeable au, Typeable av, Typeable aw, Typeable ax, Typeable ay, Typeable az, Typeable ba, Typeable bb, Typeable bc, Typeable bd, Typeable be, Typeable bf, Typeable bg, Typeable bh, Typeable bi) => Typeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be, bf, bg, bh, bi) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be, bf, bg, bh, bi) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av, toObject aw, toObject ax, toObject ay, toObject az, toObject ba, toObject bb, toObject bc, toObject bd, toObject be, toObject bf, toObject bg, toObject bh, toObject bi]


toObject :: Typeable a => a -> Value
toObject value = object ["type" .= toJSON (toType value), "data" .= toJson value]


sendValue :: Typeable a => FilePath -> a -> IO ()
sendValue file value = do
    (jsonType, jsonData) <- toJsonIO value
    LBS.appendFile file (encode (object [ "type" .= toJSON jsonType, "data" .= jsonData ]))
    
sendValueH :: Typeable a => Handle -> a -> IO ()
sendValueH file value = do
    (jsonType, jsonData) <- toJsonIO value
    LBS.hPutStr file (encode (object [ "type" .= toJSON jsonType, "data" .= jsonData ]))

toMessage :: Message -> Value
toMessage m = object [
        "description" .= toJSON (description m),
        "format" .= toJSON (format m),
        "permission" .= toJSON (permission m)
    ]

sendEvaluated :: FilePath -> EvaluationResult -> IO ()
sendEvaluated file r =
    LBS.appendFile file (encode (object [
        "result" .= toJSON (result r),
        "readable_expected" .= toJSON (readableExpected r),
        "readable_actual" .= toJSON (readableActual r),
        "messages" .= toJSON (map toMessage (messages r))
    ]))

sendEvaluatedH :: Handle -> EvaluationResult -> IO ()
sendEvaluatedH file r =
    LBS.hPutStr file (encode (object [
        "result" .= toJSON (result r),
        "readable_expected" .= toJSON (readableExpected r),
        "readable_actual" .= toJSON (readableActual r),
        "messages" .= toJSON (map toMessage (messages r))
    ]))

sendException :: Exception e => FilePath -> Maybe e -> IO ()
sendException file (Just ex) = LBS.appendFile file (encode (object [
        "message" .= toJSON (show ex),
        "stacktrace" .= toJSON (show ex)
    ]))
sendException _ Nothing = return ()
