{-# LANGUAGE FlexibleInstances, OverloadedStrings, DefaultSignatures, NamedFieldPuns #-}

module Values where

import Data.Aeson
import Data.Text (Text)
import Data.Word as W
import Data.Int as I
import Control.Exception
import qualified Data.ByteString.Lazy as LBS
import EvaluationUtils
import System.IO (Handle)
import System.IO.Unsafe (unsafePerformIO)
import Data.Typeable


-- JsonTypeable things are convertible to our format
class JsonTypeable a where
    toType :: a -> String
    toType a = "unknown"
    toJson :: a -> Value
    default toJson :: ToJSON a => a -> Value
    toJson = toJSON
    -- Function needed to unwrap IO values without needing calls to unsafeIO
    toJsonIO :: a -> IO (String, Value)
    default toJsonIO :: a -> IO (String, Value)
    toJsonIO a = return ((toType a), (toJson a))

-- We support maybe as the null value
instance (JsonTypeable a) => JsonTypeable (Maybe a) where
    toType m = case m of
        Just n -> toType n
        Nothing -> "nothing"
    toJson m = case m of
        Just n -> toJson n
        Nothing -> Null

instance (JsonTypeable a) => JsonTypeable (IO a) where
    -- Calls to `unsafePerformIO` may not produces the expected results, there for `toJsonIO` is preferred, when called
    -- this function, the student has written no clean haskell code
    {-# NOINLINE toType #-}
    toType = toType . unsafePerformIO
    -- Calls to `unsafePerformIO` may not produces the expected results, there for `toJsonIO` is preferred, when called
    -- this function, the student has written no clean haskell code
    {-# NOINLINE toJson #-}
    toJson = toJson . unsafePerformIO
    -- Preferred function call to pass the IO monad results to the judge, avoid `unsafePerformIO`
    toJsonIO m = do
        unwrapped <- m
        toJsonIO unwrapped

instance JsonTypeable W.Word8 where toType _ = "uint8"
instance JsonTypeable W.Word16 where toType _ = "uint16"
instance JsonTypeable W.Word32 where toType _ = "uint32"
instance JsonTypeable W.Word64 where toType _ = "uint64"
instance JsonTypeable I.Int8 where toType _ = "int8"
instance JsonTypeable I.Int16 where toType _ = "int16"
instance JsonTypeable I.Int32 where toType _ = "int32"
instance JsonTypeable I.Int64 where toType _ = "int64"

instance JsonTypeable Float where
    toType _ = "single_precision"
    toJson f =
        if (isNaN f) then (toJSON ("nan":: Text))
        else if (isInfinite f) && f < 0 then (toJSON ("-inf" :: Text))
        else if (isInfinite f) && f > 0 then (toJSON ("inf" :: Text))
        else (toJSON f)
instance JsonTypeable Double where
    toType _ = "double_precision"
    toJson f =
        if (isNaN f) then (toJSON ("nan":: Text))
        else if (isInfinite f) && f < 0 then (toJSON ("-inf" :: Text))
        else if (isInfinite f) && f > 0 then (toJSON ("inf" :: Text))
        else (toJSON f)
instance JsonTypeable Integer where toType _ = "bigint"
instance JsonTypeable Int where toType _ = "integer"

instance JsonTypeable Bool where toType _ = "boolean"
instance JsonTypeable Char where toType _ = "char"

instance JsonTypeable Text where toType _ = "text"
instance {-# OVERLAPPABLE #-} JsonTypeable String where toType _ = "text"

instance {-# OVERLAPPABLE #-} JsonTypeable a => JsonTypeable [a] where
    toType m = "list"
    toJson l = toJSON (map toObject l)

instance () => JsonTypeable () where
    toType _ = "undefined"
    toJson () = Null

-- Tuples, up to 62 items, as in GHC    
instance (JsonTypeable a, JsonTypeable b) => JsonTypeable (a, b) where
    toType m = "tuple"
    toJson (a, b) = toJSON [toObject a, toObject b]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c) => JsonTypeable (a, b, c) where
    toType m = "tuple"
    toJson (a, b, c) = toJSON [toObject a, toObject b, toObject c]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d) => JsonTypeable (a, b, c, d) where
    toType m = "tuple"
    toJson (a, b, c, d) = toJSON [toObject a, toObject b, toObject c, toObject d]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e) => JsonTypeable (a, b, c, d, e) where
    toType m = "tuple"
    toJson (a, b, c, d, e) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f) => JsonTypeable (a, b, c, d, e, f) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g) => JsonTypeable (a, b, c, d, e, f, g) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h) => JsonTypeable (a, b, c, d, e, f, g, h) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i) => JsonTypeable (a, b, c, d, e, f, g, h, i) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j) => JsonTypeable (a, b, c, d, e, f, g, h, i, j) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai, JsonTypeable aj) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai, JsonTypeable aj, JsonTypeable ak) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai, JsonTypeable aj, JsonTypeable ak, JsonTypeable al) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai, JsonTypeable aj, JsonTypeable ak, JsonTypeable al, JsonTypeable am) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai, JsonTypeable aj, JsonTypeable ak, JsonTypeable al, JsonTypeable am, JsonTypeable an) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai, JsonTypeable aj, JsonTypeable ak, JsonTypeable al, JsonTypeable am, JsonTypeable an, JsonTypeable ao) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai, JsonTypeable aj, JsonTypeable ak, JsonTypeable al, JsonTypeable am, JsonTypeable an, JsonTypeable ao, JsonTypeable ap) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai, JsonTypeable aj, JsonTypeable ak, JsonTypeable al, JsonTypeable am, JsonTypeable an, JsonTypeable ao, JsonTypeable ap, JsonTypeable aq) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai, JsonTypeable aj, JsonTypeable ak, JsonTypeable al, JsonTypeable am, JsonTypeable an, JsonTypeable ao, JsonTypeable ap, JsonTypeable aq, JsonTypeable ar) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai, JsonTypeable aj, JsonTypeable ak, JsonTypeable al, JsonTypeable am, JsonTypeable an, JsonTypeable ao, JsonTypeable ap, JsonTypeable aq, JsonTypeable ar, JsonTypeable as) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai, JsonTypeable aj, JsonTypeable ak, JsonTypeable al, JsonTypeable am, JsonTypeable an, JsonTypeable ao, JsonTypeable ap, JsonTypeable aq, JsonTypeable ar, JsonTypeable as, JsonTypeable at) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai, JsonTypeable aj, JsonTypeable ak, JsonTypeable al, JsonTypeable am, JsonTypeable an, JsonTypeable ao, JsonTypeable ap, JsonTypeable aq, JsonTypeable ar, JsonTypeable as, JsonTypeable at, JsonTypeable au) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai, JsonTypeable aj, JsonTypeable ak, JsonTypeable al, JsonTypeable am, JsonTypeable an, JsonTypeable ao, JsonTypeable ap, JsonTypeable aq, JsonTypeable ar, JsonTypeable as, JsonTypeable at, JsonTypeable au, JsonTypeable av) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai, JsonTypeable aj, JsonTypeable ak, JsonTypeable al, JsonTypeable am, JsonTypeable an, JsonTypeable ao, JsonTypeable ap, JsonTypeable aq, JsonTypeable ar, JsonTypeable as, JsonTypeable at, JsonTypeable au, JsonTypeable av, JsonTypeable aw) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av, toObject aw]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai, JsonTypeable aj, JsonTypeable ak, JsonTypeable al, JsonTypeable am, JsonTypeable an, JsonTypeable ao, JsonTypeable ap, JsonTypeable aq, JsonTypeable ar, JsonTypeable as, JsonTypeable at, JsonTypeable au, JsonTypeable av, JsonTypeable aw, JsonTypeable ax) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av, toObject aw, toObject ax]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai, JsonTypeable aj, JsonTypeable ak, JsonTypeable al, JsonTypeable am, JsonTypeable an, JsonTypeable ao, JsonTypeable ap, JsonTypeable aq, JsonTypeable ar, JsonTypeable as, JsonTypeable at, JsonTypeable au, JsonTypeable av, JsonTypeable aw, JsonTypeable ax, JsonTypeable ay) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av, toObject aw, toObject ax, toObject ay]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai, JsonTypeable aj, JsonTypeable ak, JsonTypeable al, JsonTypeable am, JsonTypeable an, JsonTypeable ao, JsonTypeable ap, JsonTypeable aq, JsonTypeable ar, JsonTypeable as, JsonTypeable at, JsonTypeable au, JsonTypeable av, JsonTypeable aw, JsonTypeable ax, JsonTypeable ay, JsonTypeable az) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av, toObject aw, toObject ax, toObject ay, toObject az]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai, JsonTypeable aj, JsonTypeable ak, JsonTypeable al, JsonTypeable am, JsonTypeable an, JsonTypeable ao, JsonTypeable ap, JsonTypeable aq, JsonTypeable ar, JsonTypeable as, JsonTypeable at, JsonTypeable au, JsonTypeable av, JsonTypeable aw, JsonTypeable ax, JsonTypeable ay, JsonTypeable az, JsonTypeable ba) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av, toObject aw, toObject ax, toObject ay, toObject az, toObject ba]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai, JsonTypeable aj, JsonTypeable ak, JsonTypeable al, JsonTypeable am, JsonTypeable an, JsonTypeable ao, JsonTypeable ap, JsonTypeable aq, JsonTypeable ar, JsonTypeable as, JsonTypeable at, JsonTypeable au, JsonTypeable av, JsonTypeable aw, JsonTypeable ax, JsonTypeable ay, JsonTypeable az, JsonTypeable ba, JsonTypeable bb) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av, toObject aw, toObject ax, toObject ay, toObject az, toObject ba, toObject bb]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai, JsonTypeable aj, JsonTypeable ak, JsonTypeable al, JsonTypeable am, JsonTypeable an, JsonTypeable ao, JsonTypeable ap, JsonTypeable aq, JsonTypeable ar, JsonTypeable as, JsonTypeable at, JsonTypeable au, JsonTypeable av, JsonTypeable aw, JsonTypeable ax, JsonTypeable ay, JsonTypeable az, JsonTypeable ba, JsonTypeable bb, JsonTypeable bc) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av, toObject aw, toObject ax, toObject ay, toObject az, toObject ba, toObject bb, toObject bc]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai, JsonTypeable aj, JsonTypeable ak, JsonTypeable al, JsonTypeable am, JsonTypeable an, JsonTypeable ao, JsonTypeable ap, JsonTypeable aq, JsonTypeable ar, JsonTypeable as, JsonTypeable at, JsonTypeable au, JsonTypeable av, JsonTypeable aw, JsonTypeable ax, JsonTypeable ay, JsonTypeable az, JsonTypeable ba, JsonTypeable bb, JsonTypeable bc, JsonTypeable bd) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av, toObject aw, toObject ax, toObject ay, toObject az, toObject ba, toObject bb, toObject bc, toObject bd]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai, JsonTypeable aj, JsonTypeable ak, JsonTypeable al, JsonTypeable am, JsonTypeable an, JsonTypeable ao, JsonTypeable ap, JsonTypeable aq, JsonTypeable ar, JsonTypeable as, JsonTypeable at, JsonTypeable au, JsonTypeable av, JsonTypeable aw, JsonTypeable ax, JsonTypeable ay, JsonTypeable az, JsonTypeable ba, JsonTypeable bb, JsonTypeable bc, JsonTypeable bd, JsonTypeable be) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av, toObject aw, toObject ax, toObject ay, toObject az, toObject ba, toObject bb, toObject bc, toObject bd, toObject be]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai, JsonTypeable aj, JsonTypeable ak, JsonTypeable al, JsonTypeable am, JsonTypeable an, JsonTypeable ao, JsonTypeable ap, JsonTypeable aq, JsonTypeable ar, JsonTypeable as, JsonTypeable at, JsonTypeable au, JsonTypeable av, JsonTypeable aw, JsonTypeable ax, JsonTypeable ay, JsonTypeable az, JsonTypeable ba, JsonTypeable bb, JsonTypeable bc, JsonTypeable bd, JsonTypeable be, JsonTypeable bf) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be, bf) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be, bf) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av, toObject aw, toObject ax, toObject ay, toObject az, toObject ba, toObject bb, toObject bc, toObject bd, toObject be, toObject bf]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai, JsonTypeable aj, JsonTypeable ak, JsonTypeable al, JsonTypeable am, JsonTypeable an, JsonTypeable ao, JsonTypeable ap, JsonTypeable aq, JsonTypeable ar, JsonTypeable as, JsonTypeable at, JsonTypeable au, JsonTypeable av, JsonTypeable aw, JsonTypeable ax, JsonTypeable ay, JsonTypeable az, JsonTypeable ba, JsonTypeable bb, JsonTypeable bc, JsonTypeable bd, JsonTypeable be, JsonTypeable bf, JsonTypeable bg) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be, bf, bg) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be, bf, bg) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av, toObject aw, toObject ax, toObject ay, toObject az, toObject ba, toObject bb, toObject bc, toObject bd, toObject be, toObject bf, toObject bg]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai, JsonTypeable aj, JsonTypeable ak, JsonTypeable al, JsonTypeable am, JsonTypeable an, JsonTypeable ao, JsonTypeable ap, JsonTypeable aq, JsonTypeable ar, JsonTypeable as, JsonTypeable at, JsonTypeable au, JsonTypeable av, JsonTypeable aw, JsonTypeable ax, JsonTypeable ay, JsonTypeable az, JsonTypeable ba, JsonTypeable bb, JsonTypeable bc, JsonTypeable bd, JsonTypeable be, JsonTypeable bf, JsonTypeable bg, JsonTypeable bh) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be, bf, bg, bh) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be, bf, bg, bh) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av, toObject aw, toObject ax, toObject ay, toObject az, toObject ba, toObject bb, toObject bc, toObject bd, toObject be, toObject bf, toObject bg, toObject bh]
instance (JsonTypeable a, JsonTypeable b, JsonTypeable c, JsonTypeable d, JsonTypeable e, JsonTypeable f, JsonTypeable g, JsonTypeable h, JsonTypeable i, JsonTypeable j, JsonTypeable k, JsonTypeable l, JsonTypeable m, JsonTypeable n, JsonTypeable o, JsonTypeable p, JsonTypeable q, JsonTypeable r, JsonTypeable s, JsonTypeable t, JsonTypeable u, JsonTypeable v, JsonTypeable w, JsonTypeable x, JsonTypeable y, JsonTypeable z, JsonTypeable aa, JsonTypeable ab, JsonTypeable ac, JsonTypeable ad, JsonTypeable ae, JsonTypeable af, JsonTypeable ag, JsonTypeable ah, JsonTypeable ai, JsonTypeable aj, JsonTypeable ak, JsonTypeable al, JsonTypeable am, JsonTypeable an, JsonTypeable ao, JsonTypeable ap, JsonTypeable aq, JsonTypeable ar, JsonTypeable as, JsonTypeable at, JsonTypeable au, JsonTypeable av, JsonTypeable aw, JsonTypeable ax, JsonTypeable ay, JsonTypeable az, JsonTypeable ba, JsonTypeable bb, JsonTypeable bc, JsonTypeable bd, JsonTypeable be, JsonTypeable bf, JsonTypeable bg, JsonTypeable bh, JsonTypeable bi) => JsonTypeable (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be, bf, bg, bh, bi) where
    toType m = "tuple"
    toJson (a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, ba, bb, bc, bd, be, bf, bg, bh, bi) = toJSON [toObject a, toObject b, toObject c, toObject d, toObject e, toObject f, toObject g, toObject h, toObject i, toObject j, toObject k, toObject l, toObject m, toObject n, toObject o, toObject p, toObject q, toObject r, toObject s, toObject t, toObject u, toObject v, toObject w, toObject x, toObject y, toObject z, toObject aa, toObject ab, toObject ac, toObject ad, toObject ae, toObject af, toObject ag, toObject ah, toObject ai, toObject aj, toObject ak, toObject al, toObject am, toObject an, toObject ao, toObject ap, toObject aq, toObject ar, toObject as, toObject at, toObject au, toObject av, toObject aw, toObject ax, toObject ay, toObject az, toObject ba, toObject bb, toObject bc, toObject bd, toObject be, toObject bf, toObject bg, toObject bh, toObject bi]


toObject :: JsonTypeable a => a -> Value
toObject value = object ["type" .= toJSON (toType value), "data" .= toJson value]


sendValue :: JsonTypeable a => FilePath -> a -> IO ()
sendValue file value = do
    (jsonType, jsonData) <- toJsonIO value
    LBS.appendFile file (encode (object [ "type" .= toJSON jsonType, "data" .= jsonData ]))

sendValueH :: JsonTypeable a => Handle -> a -> IO ()
sendValueH file value = do
    (jsonType, jsonData) <- toJsonIO value
    LBS.hPutStr file (encode (object [ "type" .= toJSON jsonType, "data" .= jsonData ]))

toMessage :: Message -> Value
toMessage m = object [
        "description" .= toJSON (description m),
        "format" .= toJSON (format m),
        "permission" .= toJSON (permission m)
    ]

sendEvaluated :: FilePath -> EvaluationResult -> IO ()
sendEvaluated file r =
    LBS.appendFile file (encode (object [
        "result" .= toJSON (result r),
        "readable_expected" .= toJSON (readableExpected r),
        "readable_actual" .= toJSON (readableActual r),
        "messages" .= toJSON (map toMessage (messages r))
    ]))

sendEvaluatedH :: Handle -> EvaluationResult -> IO ()
sendEvaluatedH file r =
    LBS.hPutStr file (encode (object [
        "result" .= toJSON (result r),
        "readable_expected" .= toJSON (readableExpected r),
        "readable_actual" .= toJSON (readableActual r),
        "messages" .= toJSON (map toMessage (messages r))
    ]))

sendException :: FilePath -> Maybe SomeException -> IO ()
sendException file (Just (SomeException ex)) = LBS.appendFile file (encode (object [
        "message" .= toJSON (show ex),
        "stacktrace" .= toJSON (show ex),
        "type" .= show (typeOf ex)
    ]))
sendException _ Nothing = return ()
